apiVersion: v1
kind: Service
metadata:
  name: stats-service
  labels:
    {{- include "timeseries.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 8002
  selector:
    app: stats-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-service
  labels:
    {{- include "timeseries.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-service
  template:
    metadata:
      labels:
        app: stats-service
        {{- include "timeseries.labels" . | nindent 8 }}
    spec:
      {{- if .Values.shared.pvc.enabled }}
      initContainers:
{{- include "timeseries.shared.initContainer" . | nindent 8 }}
      volumes:
{{- include "timeseries.shared.volumes" . | nindent 8 }}
      {{- end }}
      containers:
        - name: stats-service
          image: {{ .Values.images.statsService }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}

          ports:
            - containerPort: 8002

          env:
            - name: DATABASE_URL
              value: {{ printf "postgresql+psycopg2://%s:%s@processing-timescaledb:5432/timeseries" .Values.postgres.credentials.user .Values.postgres.credentials.password | quote }}

            - name: STATUS_DATABASE_URL
              value: {{ printf "postgresql+psycopg2://%s:%s@stats-status-db:5432/stats_status" .Values.postgres.credentials.user .Values.postgres.credentials.password | quote }}

            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BOOTSTRAP_SERVERS

          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 5

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

          volumeMounts:
            {{- if .Values.shared.pvc.enabled }}
{{- include "timeseries.shared.volumeMounts" . | nindent 12 }}
            {{- end }}
